name: MacOS

on:
  push:
    branches: [ "master", "dev_actions" ]
    tags: [ '**' ]

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - os: "macos-13"
            arch: x86_64
            python-version: "3.11"
            CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=11.0
          - os: "macos-14"
            arch: arm64
            python-version: "3.11"
            CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=11.0
          - os: "macos-15"
            arch: arm64
            python-version: "3.11"
            CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=11.0
    steps:
      - name: Print system info
        run: echo $(uname -o) $(uname -r) $(uname -m)
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install setuptools (needed from Python 3.12)
        run: pip install setuptools
      - name: Install Swig
        run: brew install swig
      - name: Build choco-solver-capi
        uses: ./.github/actions/build-choco-solver-capi
        with:
          os: ${{ runner.os }}
          arch: ${{ matrix.arch }}
      - name: Build pychoco
        run: |
          sh build.sh nocapibuild nowheel
          pip install pychoco -f dist/
      - name: Test
        run: |
          pip install pytest
          pip install -r requirements_tests.txt
          pytest
      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_ENVIRONMENT: ${{ matrix.CIBW_ENVIRONMENT }}
        with:
          output-dir: dist
      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{matrix.os}}-${{matrix.python-version}}-${{matrix.arch}}-artifact
          path: dist/
          if-no-files-found: error

  upload-pypi-macos:
    needs: build-macos
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        include:
          - os: "macos-13"
            arch: x86_64
            python-version: "3.11"
          - os: "macos-14"
            arch: arm64
            python-version: "3.11"
          - os: "macos-15"
            arch: arm64
            python-version: "3.11"
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: wheel-${{matrix.os}}-${{matrix.python-version}}-${{matrix.arch}}-artifact
        path: dist
    - name: List files
      run: ls -R
    - name: Upload to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
        skip-existing: true
