name: Ubuntu

on:
  push:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        config:
          - { os: ubuntu-latest,  python-version: "3.10", gu: "gu" }
          - { os: ubuntu-latest,  python-version: "3.9", gu: "gu" }
          - { os: ubuntu-latest,  python-version: "3.8", gu: "gu" }
          - { os: ubuntu-latest,  python-version: "3.7", gu: "gu" }
          - { os: ubuntu-latest,  python-version: "3.6", gu: "gu" }
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up GraalVM Native Image toolchain
        uses: helpermethod/graalvm-native-image-toolchain@0.0.2
        with:
          graalvm-version: 22.2.0
          java-version: 11
      - name: Install Swig
        run: sudo apt-get install swig
      - name: Update repository
        run: |
          git submodule update --init --recursive
      - name: Build
        run: |
          sh build.sh
          pip3 install pychoco -f dist/
      - name: Test
        run: |
          sudo apt-get install python3-pytest
          pytest-3
      - name: Generate Report
        run: |
          pip3 install coverage
          coverage run -m unittest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2