name: Ubuntu

on:
  push:
    branches: [ "master" ]
    tags: [ '**' ]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        config:
          - { os: ubuntu-latest,  python-version: "3.10" }
          - { os: ubuntu-latest,  python-version: "3.9" }
          - { os: ubuntu-latest,  python-version: "3.8" }
          - { os: ubuntu-latest,  python-version: "3.7" }
          - { os: ubuntu-latest,  python-version: "3.6" }
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}
          architecture: x64
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
      - name: Set up GraalVM Native Image toolchain
        uses: helpermethod/graalvm-native-image-toolchain@0.0.2
        with:
          graalvm-version: 22.2.0
          java-version: 11
      - name: Install Swig
        run: sudo apt-get install swig
      - name: Update repository
        run: |
          git submodule update --init --recursive
      - name: Build
        run: |
          sh build.sh
          pip3 install pychoco -f dist/
      - name: Test
        run: |
          pip3 install -r requirements_tests.txt
          sudo apt-get install python3-pytest
          pytest-3
      - name: Generate Report
        run: |
          pip3 install coverage
          coverage run -m unittest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Upload to PyPi
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
